/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    '\t\tIf problems persist, your browser might simply be too old; this could also be a problem on our side - in which case, wait a few minutes, then hit ctrl+f5!': '\t\t如果问题仍然存在，您的浏览器可能只是太旧了； 这也可能是我们这边的问题 - 在这种情况下，请等待几分钟，然后按 ctrl+f5！',
    'Got it!': '知道了!',
    'Help? Bugs? Ideas? Check out our': '需要帮助? Bugs? 好想法? 请访问我们的',
    'Legacy': '遗产',
    'loading': '加载',
    'Loading data': '加载数据',
    'NeverEnding Legacy': '无尽的遗产',
    'Pleasant': '愉快',
    'Random': '随机',
    'Start a new game': '开始新游戏',
    'Slow connection? If not, please make sure your javascript is enabled, then refresh.': '连接缓慢？ 如果没有，请确保您的 javascript 已启用，然后刷新。',
    'Research': '研究',
    'Resources': '资源',
    'Resources are scarce, and everyone starts foraging.': '资源稀缺，大家开始觅食。',
    'Territory': '领土',
    'Traits': '特点',
    'Update log': '更新日志',
    'Use mods': '使用模组',
    'World Map': '世界地图',
    'You choose to start somewhere...': '你选择从某个地方开始......',
    'You emerge as the tribe\'s leader. They call you': '你成为部落的领袖。 他们叫你',
    'Your tribe': '你的部落',
    'Your tribe finds a place to settle in the wilderness.': '你的部落在荒野中找到了一个定居点。',
    'This is taking longer than expected.': '这需要比预期更长的时间。',
    'This website uses cookies to ensure you get the best experience on our website.': '本网站使用 cookie 来确保您在我们的网站上获得最佳体验。',
    'About this alpha': '关于此版本',
    'Cookie Clicker': '无尽的饼干',
    'Cookie Consent plugin for the EU cookie law': '欧盟 cookie 法的 cookie 同意插件',
    'Policies': '政策',
    'Production': '生产',
    'Enter your name here.': '在此处输入您的名字。',
    'Log': '日志',
    'Make it something memorable!': '让它成为令人难忘的事情！',
    'Awful': '可怕',
    'Select mods for this playthrough.': '为这个游戏选择模组。',
    'Change the game\'s settings.': '修改游戏设置',
    'Features to be added later include agriculture, religion, commerce, military, and interactions with other civilizations, among other things planned.': '稍后添加的功能包括农业、宗教、商业、军事以及与其他文明的互动，以及其他计划中的内容。',
    'Feedback about bugs, oversights and technological inaccuracies are appreciated! (Send me a message to my tumblr at the top': '感谢有关错误、疏忽和技术错误的反馈！ （给我发消息到顶部的 tumblr',
    'Start your civilization in a harsh terrain with scarce natural resources.': '在自然资源稀缺的恶劣地形中开始您的文明。',
    'Start your civilization in a random place on the map.': '在地图上的随机位置开始您的文明。',
    'Start your civilization in a welcoming terrain full of natural resources.': '在充满自然资源的宜人地带开始您的文明。',
    'Thank you for playing this alpha!': '感谢您玩这个版本！',
    'The game in its current state features stone age technology and up to some parts of iron age.': '当前状态的游戏具有石器时代技术和铁器时代的某些部分。',
    'View the game\'s version history.': '查看游戏的版本历史。',
    'Who knows how your people will fare in these strange lands!': '谁知道你的人民在这些陌生的土地上会过得怎么样！',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Legacy v": "遗产 v",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+) fps$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+) Water$/, '$1 水'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);