/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    '\t\tIf problems persist, your browser might simply be too old; this could also be a problem on our side - in which case, wait a few minutes, then hit ctrl+f5!': '\t\t如果问题仍然存在，您的浏览器可能只是太旧了； 这也可能是我们这边的问题 - 在这种情况下，请等待几分钟，然后按 ctrl+f5！',
    'Got it!': '知道了!',
    'Help? Bugs? Ideas? Check out our': '需要帮助? Bugs? 好想法? 请访问我们的',
    'Legacy': '遗产',
    'loading': '加载',
    'Loading data': '加载数据',
    'NeverEnding Legacy': '无尽的遗产',
    'Pleasant': '愉快',
    'Random': '随机',
    'Start a new game': '开始新游戏',
    'Slow connection? If not, please make sure your javascript is enabled, then refresh.': '连接缓慢？ 如果没有，请确保您的 javascript 已启用，然后刷新。',
    'Research': '研究',
    'Resources': '资源',
    'Resources are scarce, and everyone starts foraging.': '资源稀缺，大家开始觅食。',
    'Territory': '领土',
    'Traits': '特点',
    'Update log': '更新日志',
    'Use mods': '使用模组',
    'World Map': '世界地图',
    'You choose to start somewhere...': '你选择从某个地方开始......',
    'You emerge as the tribe\'s leader. They call you': '你成为部落的领袖。 他们叫你',
    'Your tribe': '你的部落',
    'Your tribe finds a place to settle in the wilderness.': '你的部落在荒野中找到了一个定居点。',
    'This is taking longer than expected.': '这需要比预期更长的时间。',
    'This website uses cookies to ensure you get the best experience on our website.': '本网站使用 cookie 来确保您在我们的网站上获得最佳体验。',
    'About this alpha': '关于此版本',
    'Cookie Clicker': '无尽的饼干',
    'Cookie Consent plugin for the EU cookie law': '欧盟 cookie 法的 cookie 同意插件',
    'Policies': '政策',
    'Production': '生产',
    'Enter your name here.': '在此处输入您的名字。',
    'Log': '日志',
    'Make it something memorable!': '让它成为令人难忘的事情！',
    'Awful': '可怕',
    'Select mods for this playthrough.': '为这个游戏选择模组。',
    'Change the game\'s settings.': '修改游戏设置',
    'Features to be added later include agriculture, religion, commerce, military, and interactions with other civilizations, among other things planned.': '稍后添加的功能包括农业、宗教、商业、军事以及与其他文明的互动，以及其他计划中的内容。',
    'Feedback about bugs, oversights and technological inaccuracies are appreciated! (Send me a message to my tumblr at the top': '感谢有关错误、疏忽和技术错误的反馈！ （给我发消息到顶部的 tumblr',
    'Start your civilization in a harsh terrain with scarce natural resources.': '在自然资源稀缺的恶劣地形中开始您的文明。',
    'Start your civilization in a random place on the map.': '在地图上的随机位置开始您的文明。',
    'Start your civilization in a welcoming terrain full of natural resources.': '在充满自然资源的宜人地带开始您的文明。',
    'Thank you for playing this alpha!': '感谢您玩这个版本！',
    'The game in its current state features stone age technology and up to some parts of iron age.': '当前状态的游戏具有石器时代技术和铁器时代的某些部分。',
    'View the game\'s version history.': '查看游戏的版本历史。',
    'Who knows how your people will fare in these strange lands!': '谁知道你的人民在这些陌生的土地上会过得怎么样！',
    'One day elapses every second, and 300 days make up a year.': '每一秒都有一天过去，一年有 300 天。',
    'Known technologies': '已知技术',
    'Load': '加载',
    'Miscellaneous': '杂项',
    'New game': '新游戏',
    'It may develop some over time.': '它可能会随着时间的推移而发展。',
    'If this is your first time playing, you may want to consult some quick': '如果这是您第一次玩，您可能需要咨询一些快速',
    'Health': '健康',
    'Happiness': '幸福',
    'Getting started': '入门',
    'Gear': '齿轮',
    'Gathering': '收集',
    'Game saved -': '游戏已保存 -',
    'Food & Water': '食物 & 水',
    'Exploration': '探索',
    'Essentials': '必需品',
    'Discovery': '发现',
    'Demographics': '人口统计',
    'Date': '日期',
    'Cultural': '文化',
    'Crafting & Construction': '制作 & 建造',
    'Click the + and - buttons to increase or decrease the amount. You can ctrl-click either button to instantly make the amount negative or positive.': '单击 + 和 - 按钮以增加或减少数量。 您可以按住 ctrl 并单击任一按钮以立即使金额为负数或正数。',
    'Clear': '清理',
    'Buy amount': '购买数量',
    'average': '平均',
    'ALMIGHTY': '万能的',
    'An eerie glow from above illuminates the night.': '来自上方的诡异光芒照亮了夜晚。',
    'All Orköttas have died out.': '所有 Orköttas 都灭绝了。',
    'Population': '人口',
    'Rename civilization': '重命名文明',
    'Research (': '研究 (',
    'Reveal map': '显示地图',
    'ruler : Kot': '统治者 : Kot',
    'Scavenging': '清除',
    'Show resources': '显示资源',
    'Show tiers': '显示层',
    'The first year of your legacy has begun. May it stand the test of time.': '您遗产的第一年已经开始。 愿它经得起时间的考验。',
    'The land of Orkötta': 'Orkötta大陆',
    'The night is unforgiving.': '夜晚是无情的。',
    'This is how many units you\'ll queue or unqueue at once in a single click.': '这是您一次将要排队或取消排队的单位数量。',
    'This is the current date in your civilization.': '这是你们文明的当前日期。',
    'tips.': '提示.',
    'Total natural resources in your territory': '您领土内的自然资源总量',
    'Worms, insects, spiders -': '蠕虫、昆虫、蜘蛛—',
    'Work': '工作',
    'Welcome back -': '欢迎回来 -',
    'Uses': '使用',
    'such as fish, clams, or shrimps, is both bland-tasting and several kinds of nasty.': '例如鱼、蛤蜊或虾，味道平淡，但有几种令人讨厌。',
    'spends their time observing, thinking, and wondering why things are the way they are.': '花时间观察、思考和想知道为什么事情会变成这样。',
    'are easily caught, but are usually not considered': '很容易被抓住，但通常不被考虑',
    'are various plants, roots and mushrooms that can be collected by simply foraging around. While relatively healthy to eat, they tend to taste fairly unpleasant.': '是各种植物、根和蘑菇，可以通过简单地四处觅食来收集。 虽然吃起来相对健康，但它们的味道往往令人不快。',
    'Bugs': '虫子',
    'Dreamer': '梦想家',
    'Dry bones crack and burst underfoot.': '干燥的骨头在脚下裂开并爆裂。',
    'every now and then, which you can use to research early technologies': '不时地，您可以用它来研究早期技术',
    'Food': '食物',
    'generates': '产生',
    'Herb': '草药',
    'Herbs': '草药',
    'Insight': '洞察力',
    'Large monsters roam, unseen.': '巨大的怪物漫游，看不见。',
    'Default dataset': '默认数据集',
    'part of': '部分',
    'unlocks': '解锁',
    'unlocks policies that manage which food types can be eaten': '解锁管理可以食用哪些食物类型的政策',
    'Use your influence to enact policies that change the way your civilization functions.': '利用您的影响力制定改变您文明运作方式的政策。',
    'Various interesting things': '各种有趣的东西',
    'venture in the wilderness to gather food, wood, and other things of note.': '在荒野中冒险收集食物、木材和其他值得注意的东西。',
    'View the world map, inspect explored territory and see your natural resources.': '查看世界地图，检查已探索的领土并查看您的自然资源。',
    'View traits and edit your civilization\'s properties.': '查看特征并编辑您的文明属性。',
    'walk about in search of new places to settle, reporting what they saw when they come back.': '四处走动寻找新的定居点，报告他们回来时的所见。',
    'Wanderer': '流浪者',
    'Wanderers': '流浪者',
    'Water': '水',
    'Water rations': '水口粮',
    'Water turns into': '水变成',
    'when clean': '清洁时',
    'when other': '当其它',
    'when they get hungry, at the rate of 1 unit per person every 3 ticks (although babies and children eat less).': '当他们饿了时，每人每 3 个时刻 1 个单位（尽管婴儿和儿童吃得更少）。',
    'when your': '当你的',
    'Wisdom': '智慧',
    'Without water, people will resort to drinking': '没有水，人们会求助于饮水',
    'work': '工作',
    'Worker': '工人',
    'Workers': '工人',
    'workforce': '劳动力',
    'Workforce': '劳动力',
    'You also get 1 influence point at the start of every year.': '您还会在每年年初获得 1 个影响点。',
    'your people are given each day.': '你的人每天都被给予。',
    'Your': '你的',
    'Your people will drink': '你的人会喝',
    'A fairly soft mineral. Can be foraged from some places, but is more commonly extracted while mining or quarrying.': '一种相当软的矿物。 可以从某些地方觅食，但更常见的是在采矿或采石时提取。',
    'A short but sturdy branch. Obtained when foraging or when felling a tree.': '一个短而结实的树枝。 觅食或砍树时获得。',
    'A stream burbles quietly nearby.': '一条小溪在附近静静地流淌。',
    '(100 per fully-explored non-ocean tile, by default) upon which you can construct buildings. If for some reason you find yourself with less land than your buildings are using, some of them will start to slowly crumble away.': '（默认情况下，每个完全探索的非海洋瓷砖 100 个）您可以在其上建造建筑物。 如果出于某种原因，您发现自己的土地比建筑物使用的土地少，其中一些将开始慢慢崩溃。',
    '; working elders are more prone to accidents and early death.': '; 在职老人更容易发生事故和早逝。',
    '; working children are more prone to accidents and receive lower education.': '; 工作的儿童更容易发生事故并且受教育程度较低。',
    '; the closer to the limit, the slower it is to produce more.': '; 越接近极限，生产越慢。',
    ', which is unhealthy; if that runs out too, your people will simply die off.': '，这是不健康的； 如果它也用完了，你的人就会死掉。',
    ', whether gathered from berry bushes or fruit trees, are both sweet-tasting and good for you.': '，无论是从浆果灌木还是果树上采集的，都味道甜美，对您有好处。',
    ', used to build rudimentary structures.': '，用于构建基本结构。',
    ', unless special measures are in place.': '，除非有特别措施。',
    ', poor living conditions, and ongoing plagues.': '，恶劣的生活条件和持续的瘟疫。',
    ', in its most primitive form, is a series of groans and grunts that makes it possible to communicate things, events, and concepts.': '以其最原始的形式，是一系列的呻吟和咕噜声，使交流事物、事件和概念成为可能。',
    ', entertainment, or luxury items; things that bring down happiness are spoiled food, starvation, disease, death and harsh policies.': '、娱乐或奢侈品； 破坏幸福的事物是变质的食物、饥饿、疾病、死亡和严厉的政策。',
    ', drinking': '， 喝',
    ', but may be healed over time.': '，但随着时间的推移可能会痊愈。',
    ', although most people find them unpalatable.': '，尽管大多数人觉得它们不好吃。',
    'Current mode': '当前模式',
    'Creatures are lurking.': '生物潜伏着。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Legacy v": "遗产 v",
    "Multiply by ": "乘以 ",
    "Divide by ": "除以 ",
    "• Births : ": "• 出手 : ",
    "• Deaths : ": "• 死亡 : ",
    "Click to queue ": "点击到队列 ",
    "mod:": "模组:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+) fps$/,
    /^x([\d\.]+)$/,
    /^x([\d\.]+)k$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You accumulated (.+) fast ticks while you were away.$/, '您在离开时累积了 $1 个快速时刻。'],
    [/^Welcome back, (.+), ruler of (.+).$/, '欢迎回来，$2 的统治者 $1。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^Year ([\d\.]+), day ([\d\.]+) in Orkötta$/, '$1 年, $2 天 在Orkötta'],
	[/^([\d\.]+) year, ([\d\.]+) days$/, '$1 年, $2 天'],
	[/^Remove ([\d\.]+)$/, '减少 $1'],
	[/^Add ([\d\.]+)$/, '增加 $1'],
	[/^It is now the year (.+).$/, '现在是第 $1 年。'],
	[/^([\d\.]+) from decay$/, '$1 从衰败'],
	[/^([\d\.]+) from Gatherer$/, '$1 从收集者'],
	[/^([\d\.]+) baby has been born.$/, '$1 婴儿出生了。'],
	[/^([\d\.]+) person fell sick.$/, '$1 人感觉生病了。'],
	[/^([\d\.]+) sick person got better.$/, '$1 病人感觉好了。'],
	[/^([\d\.]+) from decay, Gatherer$/, '$1 从腐烂，收集者'],
	[/^([\d\.]+) from Fruit, Seafood$/, '$1 来自水果, 海鲜'],
	[/^([\d\.]+) from Water, Herb, Fruit$/, '$1 来自水、草药、水果'],
	[/^([\d\.]+) from Herb, no clothing, cold & darkness, health$/, '$1 来自 草药，没有衣服，寒冷和黑暗，健康'],
	[/^([\d\.]+) from Seafood, no clothing, cold & darkness, disease$/, '$1 来自 海鲜、无衣、寒冷和黑暗、疾病'],
	[/^([\d\.]+) from no clothing, cold & darkness$/, '$1 来自没有衣服，寒冷和黑暗'],
	[/^([\d\.]+) from Herb, Fruit, Bugs, Gatherer$/, '$1 从草药，水果，虫子，收集者'],
	[/^([\d\.]+) from drinking, decay$/, '$1 从饮酒，腐烂'],
	[/^([\d\.]+) from eating, decay$/, '$1 从吃，腐烂'],
	[/^([\d\.]+) people died of old age.$/, '$1 人死于年老。'],
	[/^([\d\.]+) available every day$/, '$1 每天提供'],
	[/^([\d\.]+) Insight$/, '$1 洞察力'],
	[/^([\d\.]+) Worker$/, '$1 工人'],
	[/^([\d\.]+) Food$/, '$1 食物'],
	[/^([\d\.]+) Influence$/, '$1 影响力'],
	[/^([\d\.]+) Elder$/, '$1 长老'],
	[/^([\d\.]+) Herbs$/, '$1 草药'],
	[/^([\d\.]+) Adults$/, '$1 成年人'],
	[/^([\d\.]+) Children$/, '$1 孩童'],
	[/^([\d\.]+) Water$/, '$1 水'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);